### PR TITLE
Implemented SCSS Function based on https://github.com/baumrock/Scss

### PR DESCRIPTION
**Pull request by gs-chofmann**
Hi Bernhard,

I have implemented a SASS compile function based on your code and your SCSS Plugin. I have a Pull-Request pending for the SCSS Plugin here: https://github.com/baumrock/Scss/pull/1

I have tested it in 2 projects and it works like a charm.

You might want to adopt the code to your liking.

I am not sure how you currently handle the "less" dependancy for the Less Plugin that your less function is based on. But one should probably add a dependancy for the Sass Module aswell. But I'm out on my depth on that one.

### CODE REVIEW

**Comment by BernhardBaumrock** [comment]
Hey @gs-chofmann thx for the PR, looks great!

I've merged it. I wonder if you could try to use $this->wire->files->find($path, ['extensions' => ['scss'], 'recursive' => 3]) instead of your recursive glob? Could you please try that out and maybe compare performance by adding timers?

**Comment by BernhardBaumrock** [comment]
Regarding the dependency: I don't want or can't add Scss as dependency as it will only be required if the scss compiler is required. I think the only way to handle this is to throw and error with a helpful warning message.

Also it would be great if you could add a section to the docs that explain how to use the SCSS parser:

https://www.baumrock.com/en/processwire/modules/rockfrontend/docs/asset-tools/#less-parser
https://github.com/baumrock/RockFrontend/blob/dev/docs/asset-tools/readme.md

**Comment by gs-chofmann** [comment]
Hello,

will do it in the next days, maybe to towards the weekend. It’s pretty busy here atm.

**Comment by BernhardBaumrock** [comment]
Great, thx!

**Pull request merged**
